### ISSUE TITLE
MegaDetector implementation 

### ISSUE THREAD

**Issue by mitch-fen** [genkimaps/wildcam#37]
- Run MD locally or on Azure VM (followed by face blurring?)
- Upload output .JSON alongside images
- Ability to filter by category and confidence threshold for each image:
1. Empty
2. Animal
3. Human
4. Vehicle

**Comment by genkimaps** [comment]
@mitch-fen Do you also want the bouding boxes from Megadetector displayed on the images?

**Comment by mitch-fen** [comment]
@genkimaps Having the boxes displayed would be ideal, but if this would be a major limitation the filtering ability is by far the most important aspect, including a feature for filtering by associated confidence threshold.

**Comment by genkimaps** [comment]
@mitch-fen @wildcole  Want to make sure I'm clear on the meaning of Empty.  This means that MD processed the image, but found nothing, correct?  As opposed to an image where MD was never run, so it has no MD data at all.  

When I look more deeply at the MD data structure, it's actually fairly detailed.  For each image, you may have multiple detections.  Each detection has a category, a bbox, and a confidence level.  I'd like to know how you want the filters to be applied.  

Do you want the confidence threshold to be a minimum, i.e. if there are any detections of the selected categorie(s) above the threshold, then include that image?  I assume that you do not need a separate confidence threshold for each category? 

Are the categories independent, i.e. would you want to have a checkbox for each category, so that you could check both Animal and Human in the filter?  (As opposed to a dropdown list, which would restrict to one category.)  If you select multiple categories, say Animal and Human, then I assume you would want any image that has a MD match of either Animal OR Human, rather than images with both?  

Do you need a global filter for _any image which has been processed by MD, regardless of the result_ or is that redundant? 

Conversely, do you need a filter for _any image which has NOT been processed by MD_?

If there are any other use cases you can think of, please reply here.

**Comment by mitch-fen** [comment]
@genkimaps 

1. Empty does mean MegaDetector found nothing in the image, but it was still run through the algorithm. 

2. Filtering by a confidence threshold will be necessary in some way, and would be as you described as a minimum, including any images of that category above the threshold. I'm still testing results from different environments and situations in order to discern a "good" confidence threshold broadly. Would there be potential to include a variable (box entry or otherwise) confidence value, which is user specifiable? If not we can likely go with something like 0.75 as we'll still be manually classifying afterwards. 

3. The checkbox option sounds the most optimal to me. Your human animal example is correct, although it would also be crucial to ensure that the few cases where there truly are both classes in the same image are also shown (i.e. a horseback rider, which outputs a box around the human, as well as the horse). This sounds like it would be covered with what you describe, as long as there isn't some logic statement excluding cases with multiple classes.

4. I think a box for "All" (as in all MD processed images) would be useful, especially in cases where we might be applying it to sites which were previously done without (aka all of the existing sites). A filter for "not processed by MD" would also be useful, for the inverse reason.
