### ISSUE TITLE
Add filters

### ISSUE THREAD

**Issue by mitch-fen** [genkimaps/wildcam#38]
Increase options to filter by:
- Species
- Existing Flags:
1. Favourite
2. Unprocessed
3. Collar = TRUE
4. Staff Member (this makes QA on volunteer classified images easier)

**Comment by genkimaps** [comment]
@mitch-fen Each of these flags is a true-false setting.  Do you want the filters to be able to capture both the true and false states?  Or are you only interested in:
- has species (true)
- favourite (true)
- processed (false)
- collar (true)
- staff (false?), since I assume you want to exclude staff images?

**Comment by mitch-fen** [comment]
1. has species (true)
This is correct (and already exists), but we ideally want to be able to filter by the individual species (i.e. a dropdown of the species list - so you can select all images of e.g. "Oreamnos americanus", then displaying all images tagged with this species at the given site).

2. favourite (true)
This is correct.

3. processed (false)
This is correct (makes it easier to resume where you left off within a partially completed set of photos).

4. collar (true)
This is correct. 

5. staff (false?), since I assume you want to exclude staff images?
This one is slightly different, and similar to the species filter in 1. We're looking for the ability to filter by which staff member classified the images (from the "classifier" field). This will allow us to easily error check or fix issues with photos tagged by a certain person.
