### ISSUE TITLE
Paging system for image library

### ISSUE THREAD

**Issue by mitch-fen** [genkimaps/wildcam#40]
As suggested by M.Peterman:

I suggest that in a future version, we should have a default of loading only a modest number, such as 100 images at a time, and have a widget to override this by loading a range of images.  Or a Load More button to add the next 100 images.  (In contrast to a system like Camelot, which as I recall, uses paging, and you might need to see a series of images that overlaps a page boundary).

**Comment by mitch-fen** [comment]
We might want to load something like 2-300 images, as there are cases where sequences (especially of grazing ungulates) will contain this number.

**Comment by genkimaps** [comment]
@mitch-fen @wildcole  What degree of flexibility do you want / need with this feature?  The simplest implementation would be to have a 'Load more' button that loads the next 100 images matching the current filters (100 or whatever we decide is a good default page size) .  Can also add a next / previous page button, which would jump ahead or back by the page size.   If we really want to get fancy, you could allow the user to type in a range of images, e.g. show me images 123-201 of the current set.  This could be useful if, for example, you have 50k images at a station, and you want to view the last few thousand for whatever reason (otherwise you'd have to press the next page button repeatedly to get there).  However, I don't want to make the interface too complicated.  What do you think?

**Comment by mitch-fen** [comment]
I think the "Load more" button would likely be a suitable solution. 

The last option also sounds good, but I agree it might be likely to add too much clutter/confusion/complexity. The only case where I can see something like that being used is when stopping processing a site part way through (i.e. finishing 5556/10000 image classifications), and then returning later. This is easily avoided by just using the "processed = F" filter in the current format, so is likely a non-issue.
